### plot 15: CN, FSSP, CDP, F300, CONCP, CONC1DC_LPB
RPlot15 <- function(data) {
  ## needs CONCN, CONCD_LPC, CONCF_LPT, CONC3_RPO, CONCP_RPT, CONC1DC_LPB,
  ##       CONCU, CONCU100, CONCU500, USMPFLW, USHFLW, FCNC, XICNC, PFLWC
  layout(matrix(1:2, ncol = 1), widths = 1, heights = c(5,6))
  op <- par (mar=c(2,4,1,1)+0.1,oma=c(1.1,0,0,0))
  # remove zeroes for log plot:
  data$CONCN[!is.na(data$CONCN) & (data$CONCN <= 0)] <- NA
  data$CONCU_RPC[!is.na(data$CONCU_RPC) & (data$CONCU_RPC <= 0)] <- NA
  data$CONCU100_RPC[!is.na(data$CONCU100_RPC) & (data$CONCU100_RPC <= 0)] <- NA
  data$CONCU500_RPC[!is.na(data$CONCU500_RPC) & (data$CONCU500_RPC <= 0)] <- NA
  data$CONCD_LPC[!is.na(data$CONCD_LPC) & (data$CONCD_LPC <= 0)] <- NA
  data$CONCF_LPT[!is.na(data$CONCF_LPT) & (data$CONCF_LPT <= 0)] <- NA
  #data$CONC3_RPO[!is.na(data$CONC3_RPO) & (data$CONC3_RPO <= 0)] <- NA
  data$CONCP_RPT[!is.na(data$CONCP_RPT) & (data$CONCP_RPT <= 0)] <- NA
  data$CONC1DC_LPB[!is.na(data$CONC1DC_LPB) & (data$CONC1DC_LPB <= 0)] <- NA
  plotWAC (data[, c("Time", "CONCN", "CONCP_RPT", "CONCU_RPC", "CONCU100_RPC")], 
           logxy='y', ylim=c(1,1.e5), 
           ylab=expression (paste ("CONCy [cm"^"-3"*"]")))
  op <- par (mar=c(5,4,1,1)+0.1)
  # plotWAC (data[, c("Time", "CONCD_LPC", "CONCF_LPT", "CONC3_RPO", "CONC1DC_LPB")], 
  plotWAC (data[, c("Time", "CONCD_LPC", "CONCF_LPT", "CONC1DC_LPB")], 
           logxy='y', ylim=c(0.001,1e4), ylab=expression(paste("CONCy [cm"^"-3"*"]")))
  mtext(paste(FigFooter,'generated by RPlot15',FigDatestr),1,outer=T,cex=0.75)
  op <- par (mar=c(2,4,1,1)+0.1)
  data$USHF <- data$USHFLW_RPC/10
  plotWAC (data[, c("Time", "USMPFLW_RPC", "USHF", "FCNC", "XICNC",
                    "PFLWC_RPT")], ylab="flows", legend.position='topright',
           ylim=c(0,2.5))
  hline (0.82, 'blue'); hline (1, 'darkgreen'); hline(0.5, 'red'); hline (1.5, 'red')
  legend ("topleft", legend=c("dashed red: limits for FCNC, XICNC, PFLWC", 
          "dashed blue-green: expected values for corresponding flows"), text.col=c('red', 'blue'), cex=0.55)
  title ("USHF is USHFLW_RPC/10", cex.main=0.75)
  op <- par (mar=c(5,4,1,1)+0.1)
  plotWAC (data[, c("Time", "UREF_RPC", "USCAT_RPC", "PREF_RPT")],
           ylab="laser V", legend.position='topright', ylim=c(0,10))
  hline (2.05, 'blue'); hline (1.95, 'darkgreen'); hline(6, 'red'); hline (9.95, 'red')
  title ("dashed-blue: lower limit for UREF; dashed-green: upper limit for USCAT", cex.main=0.65)
  mtext(paste(FigFooter,'generated by RPlot15',FigDatestr),1,outer=T,cex=0.75)
}

