### plot 7: dynamic pressure; also TAS and MACH
RPlot7 <- function (data) { 
  ## needs QCF, QCFR, QCR, QCFC, QCFRC, QCRC, QC_A, TASF, TASFR, 
  ## TASR, TAS_A, TASHC, MACHF, MACHFR, MACHR, MACH_A
  op <- par (mar=c(2,4,1,4)+0.1,oma=c(1.1,0,0,0))
  layout(matrix(1:2, ncol = 1), widths = 1, heights = c(5,6))
  plotWAC (data[, c("Time", "QCF", "QCFR", "QCR")], 
           col=c('blue', 'darkorange', 'darkgreen'), ylab='QCy [hPa]', legend.position=NA) # pulling legend out of plotWAC to increase font size
  legend('bottom',c("QCF", "QCFR", "QCR"),col=c("blue","darkorange","darkgreen"),text.col=c("blue","darkorange","darkgreen"),lty=1,lwd=c(2,1,1),cex=0.75)
#  points (data$Time, (data$QCF-data$QCFR)*10+80, type='l', col='red')
#  axis (4, at=c(60,80,100), labels=c("-2", "0", "2"), col='red', col.axis='red')
  par(new=T)
  plot (data$Time, (data$QCF-data$QCFR), type='l', col='red',axes=F,xlab='',ylab='',ylim=c(-4,4))
  axis (4, col='red', col.axis='red')
#  hline (60, col='red'); hline (100, col='red')
  abline(h=c(-2,2),col='red',lty=2)
#  legend("bottomleft", legend=c("red: (QCF-QCFR)*10+80", 
  legend("bottomleft", legend=c("(QCF-QCFR)", 
                                "+/- 2 hPa [diff]"), cex=0.75,lty=c(1,2),col='red')
  mtext("QCF - QCFRD [hPa]",4,col='red',3)
  op <- par (mar=c(5,4,1,4)+0.1)
  plotWAC (data[, c("Time", "QCFC", "QCFRC", "QCRC", "QC_A")], 
           col=c('blue', 'darkorange', 'darkgreen', 'brown'), ylab=' corrected QCyC [hPa]', legend.position=NA) # pulling legend out of plotWAC to increase font size
  legend('bottom',c("QCFC", "QCFRC", "QCRC", "QC_A"),col=c("blue","darkorange","darkgreen","brown"),text.col=c("blue","darkorange","darkgreen","brown"),lty=1,lwd=c(2,1,1,1),cex=0.75)
#  points (data$Time, (data$QCFC-data$QCFRC)*10+80, type='l', col='red')
#  axis (4, at=c(60,80,100), labels=c("-2", "0", "2"), col='red', col.axis='red')
  par(new=T)
  plot (data$Time, (data$QCFC-data$QCFRC), type='l', col='red',axes=F,xlab='',ylab='',ylim=c(-4,4))
  axis (4, col='red', col.axis='red')
#  hline (100, col='red'); hline (60, col='red')
  abline(h=c(-2,2),col='red',lty=2)
#  legend("bottomleft", c("red: (QCFC-QCFRC)*10+80", 
  legend("bottomleft", legend=c("(QCFC-QCFRC)", 
                                "+/- 2 hPa [diff]"), cex=0.75,lty=c(1,2),col='red')
  title (sprintf ("mean difference QCFC-QCFRC=%.1f;  QC_A-QCFRC=%.1f",
                  mean (data$QCFC-data$QCFRC, na.rm=TRUE),
                  mean (data$QC_A-data$QCFRC, na.rm=TRUE)), cex.main=0.75)
  mtext("QCFC - QCFRC [hPa]",4,col='red',3)
  mtext(paste(FigFooter,'generated by RPlot7',FigDatestr),1,outer=T,cex=0.75)
  # add TAS and MACH plots:
  op <- par (mar=c(2,4,1,1)+0.1)
  plotWAC (data[, c("Time", "TASF", "TASFR", "TASR", "TAS_A", "TASHC")], 
           col=c('blue', 'lightblue', 'darkorange', 'darkgreen', 'red'), ylab='TASy [m/s]', legend.position=NA) # pulling legend out of plotWAC to increase font size 
  legend('bottom',c("TASF", "TASFR", "TASR", "TAS_A", "TASHC"),col=c("blue","lightblue","darkorange","darkgreen","red"),text.col=c("blue","lightblue","darkorange","darkgreen","red"),lty=1,lwd=c(2,1,1,1,1),cex=0.75)
  title (sprintf ("diff vs TASF: %.1f (TASFR), %.1f (TASR), %.1f (TAS_A), %.1f (TASHC)",
                  mean (data$TASFR-data$TASF, na.rm=TRUE), 
                  mean (data$TASR-data$TASF, na.rm=TRUE), 
                  mean (data$TAS_A-data$TASF, na.rm=TRUE),
                  mean (data$TASHC-data$TASF, na.rm=TRUE)), cex.main=0.75)
  op <- par (mar=c(5,4,1,1)+0.1)
  plotWAC (data[, c("Time", "MACHF", "MACHFR", "MACHR", "MACH_A")], 
           col=c('blue', 'lightblue', 'darkorange', 'darkgreen'), ylab='MACHy', legend.position=NA)  # pulling legend out of plotWAC to increase font size
  legend('bottom',c("MACHF", "MACHFR", "MACHR", "MACH_A"),col=c("blue","lightblue","darkorange","darkgreen"),text.col=c("blue","lightblue","darkorange","darkgreen"),lty=1,lwd=c(2,1,1,1),cex=0.75)
  mtext(paste(FigFooter,'generated by RPlot7',FigDatestr),1,outer=T,cex=0.75)
}

