### plot 8: total pressure (static + dynamic)
RPlot8 <- function (data) { 
  ## needs PSFD, PSFRD, QCF, QCFR, PS_A, QC_A
  op <- par (mar=c(2,4,1,1)+0.1,oma=c(1.1,0,0,0))
  layout(matrix(1:2, ncol = 1), widths = 1, heights = c(5,6))
  DF <- data[, c("Time", "PSFD", "PSFRD")]
  DF$PSFD <- DF$PSFD + data$QCF
  DF$PSFRD <- DF$PSFRD + data$QCFR
  DF$PSA   <- data$PS_A + data$QC_A
  colnames(DF) <- c("Time", "PtotLeft", "PtotRight", "PtotAvionics")
  plotWAC (DF, col=c('blue', 'darkgreen', 'cyan'), ylab='Ptot [hPa]',legend.position=NA) # pulling legend out of plotWAC to increase font size
  legend('bottomright',c("PtotLeft", "PtotRight", "PtotAvionics"),col=c("blue","darkgreen","cyan"),text.col=c("blue","darkgreen","cyan"),lty=1,lwd=c(2,1,1),cex=0.75)
  op <- par (mar=c(5,4,1,1)+0.1)
  DF$PtotLeft <- DF$PtotLeft-DF$PtotRight
  DF$PtotRight <- NULL
  DF$PtotAvionics <- NULL
  colnames (DF) <- c("Time", "PtotDiff")
  plotWAC (DF, ylim=c(-0.5, 0.5), ylab="Ptot(left) - Ptot(right) [hPa]")
  title (sprintf ("mean difference: %.1f", 
                  mean (DF$PtotDiff, na.rm=TRUE)), cex.main=0.75)
  hline (0.2); hline (-0.2)
  mtext(paste(FigFooter,'generated by RPlot8',FigDatestr),1,outer=T,cex=0.75)
}
